cmake_minimum_required(VERSION 3.16)
project(MegalithProxy LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(megalith_proxy megalith_proxy.cpp)
target_include_directories(megalith_proxy PRIVATE ThirdParty)
target_link_libraries(megalith_proxy PRIVATE winhttp)
if(MSVC)
    set_property(TARGET megalith_proxy PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
